# Generated by Django 4.1.3 on 2022-11-07 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_comment_cteated_on_comment_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='datetime_released',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 15, 25, 17, 761454, tzinfo=datetime.timezone.utc)),
        ),
    ]
